### ISSUE TITLE
Tests fail with Nokogiri 1.13.7

### ISSUE THREAD

**Issue by radar** [instructure/nokogiri-xmlsec-instructure#12]
```
      TypeError:
        wrong argument type Nokogiri::XML::Element (expected Data)
      # ./lib/xmlsec.rb:7:in `sign!'
      # ./lib/xmlsec.rb:7:in `sign!'
      # ./spec/lib/nokogiri/xml/document/unsafe_xml_spec.rb:43:in `block (3 levels) in <top (required)>'

  58) unsafe xml guards: XML Signature URI does allow same document signing references
      Failure/Error: root.sign! opts

      TypeError:
        wrong argument type Nokogiri::XML::Element (expected Data)
      # ./lib/xmlsec.rb:7:in `sign!'
      # ./lib/xmlsec.rb:7:in `sign!'
      # ./spec/lib/nokogiri/xml/document/unsafe_xml_spec.rb:53:in `block (3 levels) in <top (required)>'
```

Just posting this here so you're aware. 

I'll see if I can get a fix through.

Possibly related to #9?
