### ISSUE TITLE
Gem install nokogiri-xmlsec-instructure failing

### ISSUE THREAD

**Issue by Loschcode** [instructure/nokogiri-xmlsec-instructure#15]
On ARM64, I can't find a way to make it work. I've looked everywhere and tried to find workarounds such as reinstalling XCode, reinstalling entirely Ruby, reinstalling a bunch of libraries with `brew`

```
gem install nokogiri-xmlsec-instructure
Building native extensions. This could take a while...
ERROR:  Error installing nokogiri-xmlsec-instructure:
	ERROR: Failed to build gem native extension.

    current directory: /Users/loschcode/.rvm/gems/ruby-3.1.0/gems/nokogiri-xmlsec-instructure-0.10.1/ext/nokogiri_ext_xmlsec
/Users/loschcode/.rvm/rubies/ruby-3.1.0/bin/ruby -I /Users/loschcode/.rvm/rubies/ruby-3.1.0/lib/ruby/site_ruby/3.1.0 extconf.rb
checking for ruby.h... yes
Clfags: -O3 -I/opt/homebrew/opt/libyaml/include -I/opt/homebrew/opt/libksba/include -I/opt/homebrew/opt/readline/include -I/opt/homebrew/opt/zlib/include -I/opt/homebrew/opt/openssl@1.1/include $(cflags) -fno-common -pipe -D__XMLSEC_FUNCTION__=__func__ -DXMLSEC_NO_SIZE_T -DXMLSEC_NO_GOST=1 -DXMLSEC_NO_GOST2012=1 -DXMLSEC_NO_CRYPTO_DYNAMIC_LOADING=1 -DXMLSEC_CRYPTO_OPENSSL=1 -D__XMLSEC_FUNCTION__=__func__ -DXMLSEC_NO_SIZE_T -DXMLSEC_NO_GOST=1 -DXMLSEC_NO_GOST2012=1 -DXMLSEC_NO_CRYPTO_DYNAMIC_LOADING=1 -I/opt/homebrew/Cellar/libxmlsec1/1.2.34_1/include/xmlsec1 -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include -I/opt/homebrew/opt/openssl@1.1/include -I/opt/homebrew/opt/openssl@1.1/include/openssl -DXMLSEC_CRYPTO_OPENSSL=1 -fvisibility=hidden
creating Makefile

current directory: /Users/loschcode/.rvm/gems/ruby-3.1.0/gems/nokogiri-xmlsec-instructure-0.10.1/ext/nokogiri_ext_xmlsec
make DESTDIR\= sitearchdir\=./.gem.20221019-14968-ujwwzw sitelibdir\=./.gem.20221019-14968-ujwwzw clean

current directory: /Users/loschcode/.rvm/gems/ruby-3.1.0/gems/nokogiri-xmlsec-instructure-0.10.1/ext/nokogiri_ext_xmlsec
make DESTDIR\= sitearchdir\=./.gem.20221019-14968-ujwwzw sitelibdir\=./.gem.20221019-14968-ujwwzw
compiling init.c
compiling nokogiri_decrypt_with_key.c
nokogiri_decrypt_with_key.c:26:15: warning: implicit conversion loses integer precision: 'long' to 'unsigned int' [-Wshorten-64-to-32]
  keyLength = RSTRING_LEN(rb_key);
            ~ ^~~~~~~~~~~~~~~~~~~
/Users/loschcode/.rvm/rubies/ruby-3.1.0/include/ruby-3.1.0/ruby/internal/core/rstring.h:52:27: note: expanded from macro 'RSTRING_LEN'
#define RSTRING_LEN       RSTRING_LEN
                          ^
1 warning generated.
compiling nokogiri_encrypt_with_key.c
nokogiri_encrypt_with_key.c:37:15: warning: implicit conversion loses integer precision: 'long' to 'unsigned int' [-Wshorten-64-to-32]
  keyLength = RSTRING_LEN(rb_rsa_key);
            ~ ^~~~~~~~~~~~~~~~~~~~~~~
/Users/loschcode/.rvm/rubies/ruby-3.1.0/include/ruby-3.1.0/ruby/internal/core/rstring.h:52:27: note: expanded from macro 'RSTRING_LEN'
#define RSTRING_LEN       RSTRING_LEN
                          ^
nokogiri_encrypt_with_key.c:47:25: warning: implicit conversion loses integer precision: 'long' to 'unsigned int' [-Wshorten-64-to-32]
    certificateLength = RSTRING_LEN(rb_cert);
                      ~ ^~~~~~~~~~~~~~~~~~~~
/Users/loschcode/.rvm/rubies/ruby-3.1.0/include/ruby-3.1.0/ruby/internal/core/rstring.h:52:27: note: expanded from macro 'RSTRING_LEN'
#define RSTRING_LEN       RSTRING_LEN
                          ^
2 warnings generated.
compiling nokogiri_helpers_set_attribute_id.c
compiling nokogiri_init.c
compiling nokogiri_sign.c
nokogiri_sign.c:59:18: warning: implicit conversion loses integer precision: 'long' to 'unsigned int' [-Wshorten-64-to-32]
  rsaKeyLength = RSTRING_LEN(rb_rsa_key);
               ~ ^~~~~~~~~~~~~~~~~~~~~~~
/Users/loschcode/.rvm/rubies/ruby-3.1.0/include/ruby-3.1.0/ruby/internal/core/rstring.h:52:27: note: expanded from macro 'RSTRING_LEN'
#define RSTRING_LEN       RSTRING_LEN
                          ^
nokogiri_sign.c:64:25: warning: implicit conversion loses integer precision: 'long' to 'unsigned int' [-Wshorten-64-to-32]
    certificateLength = RSTRING_LEN(rb_cert);
                      ~ ^~~~~~~~~~~~~~~~~~~~
/Users/loschcode/.rvm/rubies/ruby-3.1.0/include/ruby-3.1.0/ruby/internal/core/rstring.h:52:27: note: expanded from macro 'RSTRING_LEN'
#define RSTRING_LEN       RSTRING_LEN
                          ^
2 warnings generated.
compiling nokogiri_verify_with.c
nokogiri_verify_with.c:14:18: warning: implicit conversion loses integer precision: 'long' to 'int' [-Wshorten-64-to-32]
  int numCerts = RARRAY_LEN(rb_certs);
      ~~~~~~~~   ^~~~~~~~~~~~~~~~~~~~
/Users/loschcode/.rvm/rubies/ruby-3.1.0/include/ruby-3.1.0/ruby/internal/core/rarray.h:68:36: note: expanded from macro 'RARRAY_LEN'
#define RARRAY_LEN                 rb_array_len                 /**< @alias{rb_array_len} */
                                   ^
nokogiri_verify_with.c:38:18: warning: implicit conversion loses integer precision: 'long' to 'unsigned int' [-Wshorten-64-to-32]
    certLength = RSTRING_LEN(rb_cert);
               ~ ^~~~~~~~~~~~~~~~~~~~
/Users/loschcode/.rvm/rubies/ruby-3.1.0/include/ruby-3.1.0/ruby/internal/core/rstring.h:52:27: note: expanded from macro 'RSTRING_LEN'
#define RSTRING_LEN       RSTRING_LEN
                          ^
nokogiri_verify_with.c:81:19: warning: implicit conversion loses integer precision: 'long' to 'unsigned int' [-Wshorten-64-to-32]
  keyDataLength = RSTRING_LEN(rb_value);
                ~ ^~~~~~~~~~~~~~~~~~~~~
/Users/loschcode/.rvm/rubies/ruby-3.1.0/include/ruby-3.1.0/ruby/internal/core/rstring.h:52:27: note: expanded from macro 'RSTRING_LEN'
#define RSTRING_LEN       RSTRING_LEN
                          ^
nokogiri_verify_with.c:183:22: warning: implicit conversion loses integer precision: 'long' to 'unsigned int' [-Wshorten-64-to-32]
    rsa_key_length = RSTRING_LEN(rb_rsa_key);
                   ~ ^~~~~~~~~~~~~~~~~~~~~~~
/Users/loschcode/.rvm/rubies/ruby-3.1.0/include/ruby-3.1.0/ruby/internal/core/rstring.h:52:27: note: expanded from macro 'RSTRING_LEN'
#define RSTRING_LEN       RSTRING_LEN
                          ^
nokogiri_verify_with.c:212:54: warning: implicit conversion loses integer precision: 'time_t' (aka 'long') to 'int' [-Wshorten-64-to-32]
    dsigCtx->keyInfoReadCtx.certsVerificationDepth = (time_t)NUM2LONG(rb_verification_depth);
                                                   ~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
5 warnings generated.
compiling options.c
options.c:65:28: warning: implicit conversion loses integer precision: 'long' to 'int' [-Wshorten-64-to-32]
  int blockEncryptionLen = RSTRING_LEN(rb_block_encryption);
      ~~~~~~~~~~~~~~~~~~   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/loschcode/.rvm/rubies/ruby-3.1.0/include/ruby-3.1.0/ruby/internal/core/rstring.h:52:27: note: expanded from macro 'RSTRING_LEN'
#define RSTRING_LEN       RSTRING_LEN
                          ^
options.c:67:25: warning: implicit conversion loses integer precision: 'long' to 'int' [-Wshorten-64-to-32]
  int keyTransportLen = RSTRING_LEN(rb_key_transport);
      ~~~~~~~~~~~~~~~   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/loschcode/.rvm/rubies/ruby-3.1.0/include/ruby-3.1.0/ruby/internal/core/rstring.h:52:27: note: expanded from macro 'RSTRING_LEN'
#define RSTRING_LEN       RSTRING_LEN
                          ^
options.c:108:43: warning: implicit conversion loses integer precision: 'long' to 'unsigned int' [-Wshorten-64-to-32]
  unsigned int signatureAlgorithmLength = RSTRING_LEN(rb_signature_alg);
               ~~~~~~~~~~~~~~~~~~~~~~~~   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/loschcode/.rvm/rubies/ruby-3.1.0/include/ruby-3.1.0/ruby/internal/core/rstring.h:52:27: note: expanded from macro 'RSTRING_LEN'
#define RSTRING_LEN       RSTRING_LEN
                          ^
options.c:149:40: warning: implicit conversion loses integer precision: 'long' to 'unsigned int' [-Wshorten-64-to-32]
  unsigned int digestAlgorithmLength = RSTRING_LEN(rb_digest_alg);
               ~~~~~~~~~~~~~~~~~~~~~   ^~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/loschcode/.rvm/rubies/ruby-3.1.0/include/ruby-3.1.0/ruby/internal/core/rstring.h:52:27: note: expanded from macro 'RSTRING_LEN'
#define RSTRING_LEN       RSTRING_LEN
                          ^
4 warnings generated.
compiling shutdown.c
compiling util.c
linking shared-object nokogiri_ext_xmlsec.bundle
Undefined symbols for architecture arm64:
  "_noko_xml_document_pin_node", referenced from:
      _decrypt_with_key in nokogiri_decrypt_with_key.o
  "_noko_xml_node_wrap", referenced from:
      _get_id in nokogiri_helpers_set_attribute_id.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [nokogiri_ext_xmlsec.bundle] Error 1

make failed, exit code 2

Gem files will remain installed in /Users/loschcode/.rvm/gems/ruby-3.1.0/gems/nokogiri-xmlsec-instructure-0.10.1 for inspection.
Results logged to /Users/loschcode/.rvm/gems/ruby-3.1.0/extensions/arm64-darwin-21/3.1.0/nokogiri-xmlsec-instructure-0.10.1/gem_make.out
```

Any idea what's going on here?

**Comment by flavorjones** [comment]
Please try the branch in this PR: https://github.com/instructure/nokogiri-xmlsec-instructure/pull/14

**Comment by flavorjones** [comment]
Can you help me reproduce this? I'm on an ARM64 Mac, running Ruby 3.1.2, and I have Nokogiri v1.13.8 installed:

```
$ gem install nokogiri-xmlsec-instructure
Building native extensions. This could take a while...
Successfully installed nokogiri-xmlsec-instructure-0.10.1
1 gem installed
```

**Comment by flavorjones** [comment]
It looks like the undefined symbols that this gem is looking for are in Nokogiri v1.11.2 and later. You're probably on an older version?

**Comment by Loschcode** [comment]
Hi, thanks for the quick response, this is where I'm at:

```
➜  gem list | grep nokogiri
nokogiri (1.13.9 arm64-darwin)
➜  ruby -v
ruby 3.1.0p0 (2021-12-25 revision fb4df44d16) [arm64-darwin21]
```

It crashes the exact same way as I first wrote, so it would mean it's not compatible with the Nokogiri I have right now?

**Comment by flavorjones** [comment]
@Loschcode Help me reproduce what you're seeing? I am on arm64-darwin and cannot reproduce this. Can you please reply with the output from `nokogiri -v`?

**Comment by flavorjones** [comment]
(Though I will note that I tried to reproduce by installing Nokogiri from source (not precompiled) and building this gem against it ... and still could not reproduce what you're seeing.)

**Comment by Loschcode** [comment]
Oh yes there's a difference, but you should know it's because I've tried a bunch of things and I did try multiple Nokogiri versions, sadly the result is the same with the `arm64-darwin` one, here's is my `nokogiri -v`

```
# Nokogiri (1.13.9)
    ---
    warnings: []
    nokogiri:
      version: 1.13.9
      cppflags:
      - "-I/Users/loschcode/.rvm/gems/ruby-3.1.2/gems/nokogiri-1.13.9-arm64-darwin/ext/nokogiri"
      - "-I/Users/loschcode/.rvm/gems/ruby-3.1.2/gems/nokogiri-1.13.9-arm64-darwin/ext/nokogiri/include"
      - "-I/Users/loschcode/.rvm/gems/ruby-3.1.2/gems/nokogiri-1.13.9-arm64-darwin/ext/nokogiri/include/libxml2"
      ldflags: []
    ruby:
      version: 3.1.2
      platform: arm64-darwin21
      gem_platform: arm64-darwin-21
      description: ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [arm64-darwin21]
      engine: ruby
    libxml:
      source: packaged
      precompiled: true
      patches:
      - 0001-Remove-script-macro-support.patch
      - 0002-Update-entities-to-remove-handling-of-ssi.patch
      - 0003-libxml2.la-is-in-top_builddir.patch
      - 0005-avoid-isnan-isinf.patch
      - '0009-allow-wildcard-namespaces.patch'
      libxml2_path: "/Users/loschcode/.rvm/gems/ruby-3.1.2/gems/nokogiri-1.13.9-arm64-darwin/ext/nokogiri"
      memory_management: ruby
      iconv_enabled: true
      compiled: 2.10.3
      loaded: 2.10.3
    libxslt:
      source: packaged
      precompiled: true
      patches:
      - 0001-update-automake-files-for-arm64.patch
      datetime_enabled: true
      compiled: 1.1.37
      loaded: 1.1.37
    other_libraries:
      zlib: 1.2.13
      libiconv: '1.16'
      libgumbo: 1.0.0-nokogiri
```

It still crashes for me when trying to install `nokogiri-xmlsec-instructure`
